name: Deploy to SSH VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the main branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Connect to remote server via SSH to pull all changes and re-build the bot
      - name: Deploy bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/loick/github/chatgpt-bot
            nvm use 20
            npm run git
            npm i
            npm run build