name: Deploy to SSH VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the main branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js and PM2

      # Upload code to VPS using SSH
      #- name: Upload code to VPS
      #  uses: appleboy/scp-action@master
       # with:
       #   host: ${{ secrets.HOST }}
       #   username: ${{ secrets.USERNAME }}
       #   password: ${{ secrets.PASSWORD }}
      #    source: ./
      #    target: /home/loick/github/chatgpt-bot

      # Connect to remote server via SSH to start the bot using PM2
      - name: Deploy bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/loick/github/chatgpt-bot
            npm run git
            npm i
            npm run build
            pm2 reload ChatGPT
